/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_aboutDialog (void)
{
  GtkWidget *aboutDialog;
  const gchar *authors[] = {
    "Sebastian Urban <surban84@googlemail.com>",
    "Vladyslav Shtabovenko <FEW.Entwickler@googlemail.com>",
    NULL
  };
  const gchar *artists[] = {
    "Michele Ceriotti <mikelito@gmail.com>",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");
  GtkWidget *dialog_vbox2;

  aboutDialog = gtk_about_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (aboutDialog), 5);
  gtk_widget_set_events (aboutDialog, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutDialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutDialog), _("Anwendungsname"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutDialog), "Copyright (C) 2011-2012 Vladyslav Shtabovenko\nCopyright (C) 2007-2008 Sebastian Urban");
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutDialog), _("Monitors the temperature and controls the fan-speed of IBM/Lenovo ThinkPad Notebooks"));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutDialog), "This program is free software: you can redistribute it and/or modify\nit under the terms of the GNU General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\nGNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License\nalong with this program.  If not, see <http://www.gnu.org/licenses/>.");
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutDialog), "https://code.google.com/p/tpfanco/");
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutDialog), authors);
  gtk_about_dialog_set_artists (GTK_ABOUT_DIALOG (aboutDialog), artists);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutDialog), translators);

  dialog_vbox2 = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (dialog_vbox2);
  gtk_container_add (GTK_CONTAINER (aboutDialog), dialog_vbox2);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutDialog, aboutDialog, "aboutDialog");
  GLADE_HOOKUP_OBJECT (aboutDialog, dialog_vbox2, "dialog_vbox2");

  return aboutDialog;
}

GtkWidget*
create_temperatureDialog (void)
{
  GtkWidget *temperatureDialog;
  AtkObject *atko;
  GtkWidget *dialog_vbox3;
  GtkWidget *vboxState;
  GtkWidget *checkbuttonEnable;
  GtkWidget *label2;
  GtkWidget *alignmentEnable;
  GtkWidget *label9;
  GtkWidget *vboxTemperatures;
  GtkWidget *label13;
  GtkWidget *alignmentTemperatures;
  GtkWidget *vboxTriggerTemperatures;
  GtkWidget *checkbuttonOverride;
  GtkWidget *label11;
  GtkWidget *scrolledwindowThermometers;
  GtkWidget *viewportThermometers;
  GtkWidget *vboxThermometers;
  GtkWidget *hboxTemperatureUnit;
  GtkWidget *labelTemperatureUnit;
  GtkWidget *label1;
  GtkWidget *radiobuttonCelcius;
  GSList *radiobuttonCelcius_group = NULL;
  GtkWidget *radiobuttonFahrenheit;
  GSList *radiobuttonFahrenheit_group = NULL;
  GtkWidget *hseparator2;
  GtkWidget *expanderAdvanced;
  GtkWidget *vboxAdvancedOut;
  GtkWidget *alignmentAdvanced;
  GtkWidget *vboxAdvanced;
  GtkWidget *vboxHysteresis;
  GtkWidget *label3;
  GtkWidget *hbox1;
  GtkWidget *hscaleHysteresis;
  GtkWidget *labelHysteresisUnit;
  GtkWidget *hseparator4;
  GtkWidget *label4;
  GtkWidget *hboxMonitor;
  GtkWidget *vboxMonitor;
  GtkWidget *label14;
  GtkWidget *alignmentMonitor;
  GtkWidget *tableModel;
  GtkWidget *viewportProfileComments;
  GtkWidget *textviewProfileComments;
  GtkWidget *label5;
  GtkWidget *entryProfile;
  GtkWidget *entryModel;
  GtkWidget *label17;
  GtkWidget *label15;
  GtkWidget *alignment1;
  GtkWidget *vbox2;
  GtkWidget *labelSpeed;
  GtkWidget *labelLevel;
  GtkWidget *dialog_action_area;
  GtkWidget *buttonAbout;
  GtkWidget *buttonSubmitProfile;
  GtkWidget *buttonClose;

  temperatureDialog = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (temperatureDialog), 5);
  gtk_widget_set_events (temperatureDialog, GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK);
  gtk_window_set_title (GTK_WINDOW (temperatureDialog), _("Configure tpfancod"));
  gtk_window_set_position (GTK_WINDOW (temperatureDialog), GTK_WIN_POS_CENTER);
  gtk_window_set_type_hint (GTK_WINDOW (temperatureDialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (temperatureDialog), FALSE);

  dialog_vbox3 = GTK_DIALOG (temperatureDialog)->vbox;
  gtk_widget_show (dialog_vbox3);

  vboxState = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxState);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vboxState, FALSE, TRUE, 0);

  checkbuttonEnable = gtk_check_button_new ();
  gtk_widget_show (checkbuttonEnable);
  gtk_box_pack_start (GTK_BOX (vboxState), checkbuttonEnable, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("<b>Control system fan by software</b>"));
  gtk_widget_show (label2);
  gtk_container_add (GTK_CONTAINER (checkbuttonEnable), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  alignmentEnable = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignmentEnable);
  gtk_box_pack_start (GTK_BOX (vboxState), alignmentEnable, FALSE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignmentEnable), 0, 0, 30, 0);

  label9 = gtk_label_new (_("Allows you to make your computer quieter by configuring the system fan to turn on at higher temperatures \nthan specified by the manufacturer.\n<b>You can damage or shorten the lifespan of your computer by allowing too high temperatures.</b>"));
  gtk_widget_show (label9);
  gtk_container_add (GTK_CONTAINER (alignmentEnable), label9);
  gtk_label_set_use_markup (GTK_LABEL (label9), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0);

  vboxTemperatures = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxTemperatures);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), vboxTemperatures, TRUE, TRUE, 0);

  label13 = gtk_label_new (_("<b>Temperatures</b>"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (vboxTemperatures), label13, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label13), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  alignmentTemperatures = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignmentTemperatures);
  gtk_box_pack_start (GTK_BOX (vboxTemperatures), alignmentTemperatures, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignmentTemperatures), 0, 0, 30, 0);

  vboxTriggerTemperatures = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxTriggerTemperatures);
  gtk_container_add (GTK_CONTAINER (alignmentTemperatures), vboxTriggerTemperatures);
  gtk_container_set_border_width (GTK_CONTAINER (vboxTriggerTemperatures), 5);

  checkbuttonOverride = gtk_check_button_new ();
  gtk_widget_show (checkbuttonOverride);
  gtk_box_pack_start (GTK_BOX (vboxTriggerTemperatures), checkbuttonOverride, FALSE, FALSE, 0);

  label11 = gtk_label_new (_("Manually configure system fan trigger temperatures"));
  gtk_widget_show (label11);
  gtk_container_add (GTK_CONTAINER (checkbuttonOverride), label11);
  gtk_label_set_use_markup (GTK_LABEL (label11), TRUE);

  scrolledwindowThermometers = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindowThermometers);
  gtk_box_pack_start (GTK_BOX (vboxTriggerTemperatures), scrolledwindowThermometers, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindowThermometers), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  viewportThermometers = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewportThermometers);
  gtk_container_add (GTK_CONTAINER (scrolledwindowThermometers), viewportThermometers);

  vboxThermometers = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vboxThermometers);
  gtk_container_add (GTK_CONTAINER (viewportThermometers), vboxThermometers);
  gtk_container_set_border_width (GTK_CONTAINER (vboxThermometers), 2);

  hboxTemperatureUnit = gtk_hbox_new (FALSE, 6);
  gtk_widget_show (hboxTemperatureUnit);
  gtk_box_pack_start (GTK_BOX (vboxTriggerTemperatures), hboxTemperatureUnit, FALSE, TRUE, 0);

  labelTemperatureUnit = gtk_label_new ("");
  gtk_widget_show (labelTemperatureUnit);
  gtk_box_pack_start (GTK_BOX (hboxTemperatureUnit), labelTemperatureUnit, FALSE, TRUE, 0);
  gtk_label_set_use_markup (GTK_LABEL (labelTemperatureUnit), TRUE);
  gtk_misc_set_alignment (GTK_MISC (labelTemperatureUnit), 0, 0.5);

  label1 = gtk_label_new ("");
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hboxTemperatureUnit), label1, TRUE, TRUE, 0);

  radiobuttonCelcius = gtk_radio_button_new_with_mnemonic (NULL, _("\302\260C"));
  gtk_widget_show (radiobuttonCelcius);
  gtk_box_pack_start (GTK_BOX (hboxTemperatureUnit), radiobuttonCelcius, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonCelcius), radiobuttonCelcius_group);
  radiobuttonCelcius_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonCelcius));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobuttonCelcius), TRUE);

  radiobuttonFahrenheit = gtk_radio_button_new_with_mnemonic (NULL, _("\302\260F"));
  gtk_widget_show (radiobuttonFahrenheit);
  gtk_box_pack_start (GTK_BOX (hboxTemperatureUnit), radiobuttonFahrenheit, FALSE, FALSE, 0);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobuttonFahrenheit), radiobuttonFahrenheit_group);
  radiobuttonFahrenheit_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobuttonFahrenheit));
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (radiobuttonFahrenheit), TRUE);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_box_pack_start (GTK_BOX (vboxTriggerTemperatures), hseparator2, FALSE, TRUE, 0);

  expanderAdvanced = gtk_expander_new (NULL);
  gtk_widget_show (expanderAdvanced);
  gtk_box_pack_start (GTK_BOX (vboxTriggerTemperatures), expanderAdvanced, FALSE, TRUE, 0);

  vboxAdvancedOut = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxAdvancedOut);
  gtk_container_add (GTK_CONTAINER (expanderAdvanced), vboxAdvancedOut);

  alignmentAdvanced = gtk_alignment_new (0, 0.5, 1, 1);
  gtk_widget_show (alignmentAdvanced);
  gtk_box_pack_start (GTK_BOX (vboxAdvancedOut), alignmentAdvanced, TRUE, TRUE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignmentAdvanced), 0, 0, 25, 0);

  vboxAdvanced = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxAdvanced);
  gtk_container_add (GTK_CONTAINER (alignmentAdvanced), vboxAdvanced);

  vboxHysteresis = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxHysteresis);
  gtk_box_pack_start (GTK_BOX (vboxAdvanced), vboxHysteresis, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Hysteresis"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vboxHysteresis), label3, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label3), 0, 0.5);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vboxHysteresis), hbox1, TRUE, TRUE, 0);

  hscaleHysteresis = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (3.77, 0, 10, 1, 0, 0)));
  gtk_widget_show (hscaleHysteresis);
  gtk_box_pack_start (GTK_BOX (hbox1), hscaleHysteresis, TRUE, TRUE, 14);
  gtk_scale_set_digits (GTK_SCALE (hscaleHysteresis), 0);

  labelHysteresisUnit = gtk_label_new (_("\302\260K"));
  gtk_widget_show (labelHysteresisUnit);
  gtk_box_pack_start (GTK_BOX (hbox1), labelHysteresisUnit, FALSE, TRUE, 0);
  gtk_misc_set_padding (GTK_MISC (labelHysteresisUnit), 5, 0);

  hseparator4 = gtk_hseparator_new ();
  gtk_widget_show (hseparator4);
  gtk_box_pack_start (GTK_BOX (vboxAdvancedOut), hseparator4, FALSE, TRUE, 0);

  label4 = gtk_label_new (_("Advanced options"));
  gtk_widget_show (label4);
  gtk_expander_set_label_widget (GTK_EXPANDER (expanderAdvanced), label4);

  hboxMonitor = gtk_hbox_new (FALSE, 15);
  gtk_widget_show (hboxMonitor);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), hboxMonitor, FALSE, FALSE, 0);

  vboxMonitor = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vboxMonitor);
  gtk_box_pack_start (GTK_BOX (hboxMonitor), vboxMonitor, TRUE, TRUE, 0);

  label14 = gtk_label_new (_("<b>Monitoring</b>"));
  gtk_widget_show (label14);
  gtk_box_pack_start (GTK_BOX (vboxMonitor), label14, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  alignmentMonitor = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignmentMonitor);
  gtk_box_pack_start (GTK_BOX (vboxMonitor), alignmentMonitor, FALSE, FALSE, 0);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignmentMonitor), 0, 0, 30, 0);

  tableModel = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (tableModel);
  gtk_container_add (GTK_CONTAINER (alignmentMonitor), tableModel);
  gtk_table_set_col_spacings (GTK_TABLE (tableModel), 12);

  viewportProfileComments = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewportProfileComments);
  gtk_table_attach (GTK_TABLE (tableModel), viewportProfileComments, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 1, 1);

  textviewProfileComments = gtk_text_view_new ();
  gtk_widget_show (textviewProfileComments);
  gtk_container_add (GTK_CONTAINER (viewportProfileComments), textviewProfileComments);
  gtk_text_view_set_pixels_below_lines (GTK_TEXT_VIEW (textviewProfileComments), 4);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textviewProfileComments)), _("Profile comments"), -1);

  label5 = gtk_label_new (_("Profile information"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (tableModel), label5, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label5), 0, 0);
  gtk_misc_set_padding (GTK_MISC (label5), 0, 2);

  entryProfile = gtk_entry_new ();
  gtk_widget_show (entryProfile);
  gtk_table_attach (GTK_TABLE (tableModel), entryProfile, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entryProfile), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entryProfile), "Generic");
  gtk_entry_set_invisible_char (GTK_ENTRY (entryProfile), 8226);

  entryModel = gtk_entry_new ();
  gtk_widget_show (entryModel);
  gtk_table_attach (GTK_TABLE (tableModel), entryModel, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_editable_set_editable (GTK_EDITABLE (entryModel), FALSE);
  gtk_entry_set_text (GTK_ENTRY (entryModel), "Lenovo ThinkPad XXX");
  gtk_entry_set_invisible_char (GTK_ENTRY (entryModel), 8226);

  label17 = gtk_label_new (_("Used fan profiles"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (tableModel), label17, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label15 = gtk_label_new (_("Notebook model"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (tableModel), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_box_pack_start (GTK_BOX (hboxMonitor), alignment1, FALSE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (alignment1), vbox2);

  labelSpeed = gtk_label_new (_("2000 RPM"));
  gtk_widget_show (labelSpeed);
  gtk_box_pack_start (GTK_BOX (vbox2), labelSpeed, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (labelSpeed), 8, 10);

  labelLevel = gtk_label_new (_("Level 2"));
  gtk_widget_show (labelLevel);
  gtk_box_pack_start (GTK_BOX (vbox2), labelLevel, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (labelLevel), 0.5, 0.46);
  gtk_misc_set_padding (GTK_MISC (labelLevel), 0, 6);

  dialog_action_area = GTK_DIALOG (temperatureDialog)->action_area;
  gtk_widget_show (dialog_action_area);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area), GTK_BUTTONBOX_END);

  buttonAbout = gtk_button_new_from_stock ("gtk-about");
  gtk_widget_show (buttonAbout);
  gtk_dialog_add_action_widget (GTK_DIALOG (temperatureDialog), buttonAbout, 0);

  buttonSubmitProfile = gtk_button_new_with_mnemonic (_("Submit profile..."));
  gtk_widget_show (buttonSubmitProfile);
  gtk_dialog_add_action_widget (GTK_DIALOG (temperatureDialog), buttonSubmitProfile, 0);

  buttonClose = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (buttonClose);
  gtk_dialog_add_action_widget (GTK_DIALOG (temperatureDialog), buttonClose, 1);

  atko = gtk_widget_get_accessible (temperatureDialog);
  atk_object_set_name (atko, _("Configure tpfanco"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (temperatureDialog, temperatureDialog, "temperatureDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (temperatureDialog, dialog_vbox3, "dialog_vbox3");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxState, "vboxState");
  GLADE_HOOKUP_OBJECT (temperatureDialog, checkbuttonEnable, "checkbuttonEnable");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label2, "label2");
  GLADE_HOOKUP_OBJECT (temperatureDialog, alignmentEnable, "alignmentEnable");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label9, "label9");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxTemperatures, "vboxTemperatures");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label13, "label13");
  GLADE_HOOKUP_OBJECT (temperatureDialog, alignmentTemperatures, "alignmentTemperatures");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxTriggerTemperatures, "vboxTriggerTemperatures");
  GLADE_HOOKUP_OBJECT (temperatureDialog, checkbuttonOverride, "checkbuttonOverride");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label11, "label11");
  GLADE_HOOKUP_OBJECT (temperatureDialog, scrolledwindowThermometers, "scrolledwindowThermometers");
  GLADE_HOOKUP_OBJECT (temperatureDialog, viewportThermometers, "viewportThermometers");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxThermometers, "vboxThermometers");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hboxTemperatureUnit, "hboxTemperatureUnit");
  GLADE_HOOKUP_OBJECT (temperatureDialog, labelTemperatureUnit, "labelTemperatureUnit");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label1, "label1");
  GLADE_HOOKUP_OBJECT (temperatureDialog, radiobuttonCelcius, "radiobuttonCelcius");
  GLADE_HOOKUP_OBJECT (temperatureDialog, radiobuttonFahrenheit, "radiobuttonFahrenheit");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (temperatureDialog, expanderAdvanced, "expanderAdvanced");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxAdvancedOut, "vboxAdvancedOut");
  GLADE_HOOKUP_OBJECT (temperatureDialog, alignmentAdvanced, "alignmentAdvanced");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxAdvanced, "vboxAdvanced");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxHysteresis, "vboxHysteresis");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label3, "label3");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hscaleHysteresis, "hscaleHysteresis");
  GLADE_HOOKUP_OBJECT (temperatureDialog, labelHysteresisUnit, "labelHysteresisUnit");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hseparator4, "hseparator4");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label4, "label4");
  GLADE_HOOKUP_OBJECT (temperatureDialog, hboxMonitor, "hboxMonitor");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vboxMonitor, "vboxMonitor");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label14, "label14");
  GLADE_HOOKUP_OBJECT (temperatureDialog, alignmentMonitor, "alignmentMonitor");
  GLADE_HOOKUP_OBJECT (temperatureDialog, tableModel, "tableModel");
  GLADE_HOOKUP_OBJECT (temperatureDialog, viewportProfileComments, "viewportProfileComments");
  GLADE_HOOKUP_OBJECT (temperatureDialog, textviewProfileComments, "textviewProfileComments");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label5, "label5");
  GLADE_HOOKUP_OBJECT (temperatureDialog, entryProfile, "entryProfile");
  GLADE_HOOKUP_OBJECT (temperatureDialog, entryModel, "entryModel");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label17, "label17");
  GLADE_HOOKUP_OBJECT (temperatureDialog, label15, "label15");
  GLADE_HOOKUP_OBJECT (temperatureDialog, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (temperatureDialog, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (temperatureDialog, labelSpeed, "labelSpeed");
  GLADE_HOOKUP_OBJECT (temperatureDialog, labelLevel, "labelLevel");
  GLADE_HOOKUP_OBJECT_NO_REF (temperatureDialog, dialog_action_area, "dialog_action_area");
  GLADE_HOOKUP_OBJECT (temperatureDialog, buttonAbout, "buttonAbout");
  GLADE_HOOKUP_OBJECT (temperatureDialog, buttonSubmitProfile, "buttonSubmitProfile");
  GLADE_HOOKUP_OBJECT (temperatureDialog, buttonClose, "buttonClose");

  return temperatureDialog;
}

GtkWidget*
create_sensornameDialog (void)
{
  GtkWidget *sensornameDialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *vbox1;
  GtkWidget *labelTitle;
  GtkWidget *entrySensorName;
  GtkWidget *dialog_action_area4;
  GtkWidget *buttonOk;
  GtkWidget *buttonCancel;

  sensornameDialog = gtk_dialog_new ();
  gtk_container_set_border_width (GTK_CONTAINER (sensornameDialog), 5);
  gtk_window_set_title (GTK_WINDOW (sensornameDialog), _("Change sensor name"));
  gtk_window_set_default_size (GTK_WINDOW (sensornameDialog), 200, -1);
  gtk_window_set_resizable (GTK_WINDOW (sensornameDialog), FALSE);
  gtk_window_set_skip_taskbar_hint (GTK_WINDOW (sensornameDialog), TRUE);
  gtk_window_set_type_hint (GTK_WINDOW (sensornameDialog), GDK_WINDOW_TYPE_HINT_DIALOG);
  gtk_dialog_set_has_separator (GTK_DIALOG (sensornameDialog), FALSE);

  dialog_vbox4 = GTK_DIALOG (sensornameDialog)->vbox;
  gtk_widget_show (dialog_vbox4);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), vbox1, TRUE, TRUE, 0);

  labelTitle = gtk_label_new ("Name for sensor 1");
  gtk_widget_show (labelTitle);
  gtk_box_pack_start (GTK_BOX (vbox1), labelTitle, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (labelTitle), 0, 0.5);

  entrySensorName = gtk_entry_new ();
  gtk_widget_show (entrySensorName);
  gtk_box_pack_start (GTK_BOX (vbox1), entrySensorName, FALSE, FALSE, 0);
  gtk_entry_set_max_length (GTK_ENTRY (entrySensorName), 10);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrySensorName), 8226);
  gtk_entry_set_activates_default (GTK_ENTRY (entrySensorName), TRUE);

  dialog_action_area4 = GTK_DIALOG (sensornameDialog)->action_area;
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_END);

  buttonOk = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (buttonOk);
  gtk_dialog_add_action_widget (GTK_DIALOG (sensornameDialog), buttonOk, 1);
  GTK_WIDGET_SET_FLAGS (buttonOk, GTK_CAN_DEFAULT);

  buttonCancel = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (buttonCancel);
  gtk_dialog_add_action_widget (GTK_DIALOG (sensornameDialog), buttonCancel, 2);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (sensornameDialog, sensornameDialog, "sensornameDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (sensornameDialog, dialog_vbox4, "dialog_vbox4");
  GLADE_HOOKUP_OBJECT (sensornameDialog, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (sensornameDialog, labelTitle, "labelTitle");
  GLADE_HOOKUP_OBJECT (sensornameDialog, entrySensorName, "entrySensorName");
  GLADE_HOOKUP_OBJECT_NO_REF (sensornameDialog, dialog_action_area4, "dialog_action_area4");
  GLADE_HOOKUP_OBJECT (sensornameDialog, buttonOk, "buttonOk");
  GLADE_HOOKUP_OBJECT (sensornameDialog, buttonCancel, "buttonCancel");

  gtk_widget_grab_focus (entrySensorName);
  gtk_widget_grab_default (buttonOk);
  return sensornameDialog;
}

